### ISSUE TITLE
Draw inspiration from already existing projects

### ISSUE THREAD

**Issue by dkbast** [matthewsot/docs-vim#1]
Hi! Your project is awesome - Im really looking forward to seeing you succeed! Maybe you can draw some inspiration from those javascript based vim implementations or maybe even consider using some of their code or using one of this projects as a starting point :)
https://github.com/akahuku/wasavi
https://github.com/toplan/Vim.js
https://github.com/coolwanglu/vim.js

Keep up the good work !

**Comment by matthewsot** [comment]
Thanks for the links! It's hard to directly port a lot of that because Google's editor is so weird, but they're definitely great references/starting points for some of the backend work that needs to be done :)
