### ISSUE TITLE
undo

### ISSUE THREAD

**Issue by TipOfTheSploit** [matthewsot/docs-vim#5]
I've tried for the last couple hours to implement undo <"u"> in normal mode to no avail.  Tried docs.execCommand("undo"); and various other things.  Any thoughts on ways to do this or interest in implementing?  Happy to implement myself if I get a hint on how to do it.

**Comment by lovetocode999** [comment]
Have you tried ```docs.pressKey("z", true)```?

**Comment by TipOfTheSploit** [comment]
Unfortunately, it doesn't.  It does seem like it should...

**Comment by lovetocode999** [comment]
Hmmm. What about ```docs.pressKey("z", true, false)```? If that doesn't work either, then it might be a problem with docs-plus.

**Comment by TipOfTheSploit** [comment]
That is failing as well:( This is a great project, I'll try other things soon

**Comment by matthewsot** [comment]
Thanks for reaching out! `docs.pressKey(docs.codeFromKey("z"), true, false)` should work, and in fact we do similar things to implement toggle bold, toggle subscript, etc. However, as you mention, it doesn't. I've tried to debug this a bit (e.g. sending explicit keydown/keyup fake ctrl-key presses before and after) but it looks like Docs is using a different mechanism to check for ctrl+z/ctrl+y than other key combinations.

Ideally, if someone can figure out what it's looking for, we can modify `docs.pressKey` (or add a similar function) to support that.

However, for the time being, a workaround is to actually just press the undo/redo menu options. You can add the following to `docs-plus/docs.js` to do this:

```javascript
docs.undo = function () {
    var el = $("[aria-label='Undo u']")[0];
    el.dispatchEvent(new MouseEvent("mouseenter", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mouseleave", { bubbles: true }));
};

docs.redo = function () {
    var el = $("[aria-label='Redo r']")[0];
    el.dispatchEvent(new MouseEvent("mouseenter", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    el.dispatchEvent(new MouseEvent("mouseleave", { bubbles: true }));
};
```

This seems to work for me. Not all of the dispatchEvents may be necessary, I haven't tried figuring out which ones.

Let me know if it works for you!

If that works for you, I can make the change in `docs-plus` today. Note you may have to undo/reset any changes to `docs-plus/` before pulling the updated `docs-plus` once that's done (I'm not _entirely_ sure how git submodules works in this scenario...).

(On a side note @lovetocode999 sorry for ghosting the PR --- I'll take a look right after this!)

**Comment by TipOfTheSploit** [comment]
Everything about this issue interaction is amazing.  Thank you @lovetocode999 and @matthewsot.  So grateful to both of you for caring about this.

**Comment by matthewsot** [comment]
Of course, thanks for opening the issue! I've pushed up https://github.com/matthewsot/docs-plus/commit/e8ffe5e7bb1a9983a39eac21389867dd1aa0cbfe which should resolve the issue.

To get it to update in `docs-vim`, you will probably need to run:
```bash
cd docs-vim  # docs-vim repository root
cd docs-plus
git checkout -- docs.js  # assuming you had modified docs.js
git pull
```
You can verify by checking `test.js` calls `docs.undo()`.

Feel free to let me know if it still doesn't work, or close the issue if it's resolved :) And please do send a PR if you get undo working in normal mode!

**Comment by matthewsot** [comment]
Closing for now, feel free to re-open if it doesn't work.
